version: '3'
services:
  finder-backend:
    restart: always
    container_name: compose_finder-backend
    build:
      context: ./finder-backend
      dockerfile: ./Dockerfile
    networks:
      - mynetwork
    external_links:
      - 'compose_mongodb:mongo'
    ports:
      - '4000:4000'
    volumes:
      - 'track_folder:/docs'
    image: 'freedom-lab/finder-backend:v1'

  finder-frontend:
    restart: always
    container_name: compose_finder-frontend
    build:
      context: ./finder-frontend
      dockerfile: ./Dockerfile
    networks:
      - mynetwork
    links:
      - 'finder-backend:finder-backend'
    ports:
      - '8800:80'
    image: 'freedom-lab/finder-frontend:v1'

volumes:
  track_folder:
    driver: local
    driver_opts:
      type: none
      device: /Volumes/Second_Disk/Dropbox/Docs/
      o: bind

networks:
  mynetwork:
    external: true
